### ISSUE TITLE
Fire event when JS is initiated

### ISSUE THREAD

**Issue by adi-** [deschler/django-modeltranslation#714]
When all translation inputs are initiated it would be nice to fire an event. I am manipulating form inputs (setting custom height), but I am having a race condition. My script is run when DOM is loaded, same with django-modeltranslation JS scripts. My manipulation script sometimes can't see those form inputs, because of not finished django-translation scripts.

Any chance to do so?

**Comment by last-partizan** [comment]
Sure. Please take a look at JS code and make a PR with this event you need.

I can do code review and merge it.

**Comment by adi-** [comment]
OK, I have spotted the real problem. Tabs switch content with setting `display: none` on them. Any chance to use `visibility: hidden`? Original one removes content from layout, second one allows to do extra manipulations on inputs.

**Comment by last-partizan** [comment]
In theory: yes.

Feel free to experiment with code and get it to do what you want.

Best to use your own fork for some time, and if all works fine, make PR.

**Comment by adi-** [comment]
For reference: Problem is with jQuery's UI Tabs widget which `django-modeltranslation` uses. They use standard jQuery's `.show()` `.hide()` functions that manipulate css `display` setting it to `none`. Simple workaround is overriding classes that set state on tab's content:

```css
/* Override jQuery UI Tabs hiding behavior in Django admin to avoid display:none issues with tabbed widgets (e.g. django-modeltranslation tabs). */
.ui-tabs-panel[aria-hidden="true"] {
    display: block !important;
    visibility: hidden;
    position: absolute;
    pointer-events: none;
    opacity: 0;
}
.ui-tabs-panel[aria-hidden="false"] {
    visibility: visible;
    position: relative;
    pointer-events: auto;
    opacity: 1;
}
```
